### ISSUE TITLE
MAS1D-Extender

### ISSUE THREAD

**Issue by heroinedor** [eimis-ans/eimis-synapse#107]
Solution to avoid discory-room : https://github.com/cameronwickes/ma1sd-extender

tasklist : 
- [ ] study this option
- [ ] install it on our infra (kubernetes object)
- [ ] plug it with our synapse server
- [ ] see if it fits our needs for editor integration

**Comment by heroinedor** [comment]
Solution to avoid discory-room : https://github.com/cameronwickes/ma1sd-extender

tasklist : 
- [ ] study this option
- [ ] install it on our infra (kubernetes object)
- [ ] plugi it with our synapse server

**Comment by ad2ien** [comment]
🤔 The image doesn't start properly... although the the solution appears better than the discovery room it would require to take the project over to fix and improve it.

**Comment by ad2ien** [comment]
- [x] project forked and some refactor done : https://github.com/eimis-ans/ma1sd-extender/pull/1
- [x] introduced in the stack : https://github.com/eimis-ans/eimis-synapse/tree/feat/ma1sd-extender-not-ready

Issue : impossible to request other matrix federation instances with a user from the running instance...
