### ISSUE TITLE
Monitoring matrix federation

### ISSUE THREAD

**Issue by ad2ien** [eimis-ans/eimis-synapse#113]
## Purpose

As part of this summer experimentation it would be interesting to setup an infrastructure to get metrics about matrix use.

## How

Synapse exports some metrics : https://matrix-org.github.io/synapse/latest/metrics-howto.html
Here are the metrics regarding the federation:
- synapse_federation_client_sent_transactions_total
- synapse_federation_client_events_processed_total
- synapse_federation_server_received_pdus_total
- synapse_federation_server_received_edus_total
- synapse_handler_presence_federation_presence_total
- synapse_federation_client_sent_edus_total
- synapse_federation_client_sent_pdu_destinations_count_total
- synapse_federation_client_sent_pdu_destinations_total
 
And an helpful resource : https://matrix-org.github.io/synapse/latest/usage/administration/understanding_synapse_through_grafana_graphs.html

## Who

- We could host and monitor an homeserver as part of the federation but it may need to be [HDS](https://esante.gouv.fr/labels-certifications/hds/certification-des-hebergeurs-de-donnees-de-sante) compliant.
- We need one of our active partner to give us access to the part of their dashboard that monitors matrix federation

**Comment by ad2ien** [comment]
A Grafana Dashboard for synapse : https://grafana.com/grafana/dashboards/13894-synapse/

**Comment by heroinedor** [comment]
Nice to have : can we extract some functional metrics from this technical metrics ?
=> maybe it is worth to create antoher ticket ?
