### ISSUE TITLE
Get more knowledge about the architecture options for the directory

### ISSUE THREAD

**Issue by JDixmier** [eimis-ans/eimis-synapse#115]

**Comment by JDixmier** [comment]
Tasklist:
- [ ] Workshop with Julien : brainstorming and challenge on different possible options
- [ ] Workshop with Gematik  :  how do they solved this problem ?
- [x] Matrix documentation about Distributed IDs 
- [ ] How to plug to the user directory search mechanism on matrix
- [ ] Directory federation ?

Definition of done : 
Get ideas clear enough to submit some options to partners during the next open lab on this subject

**Comment by ad2ien** [comment]
Portable Identities topic in the Matrix youtube channel : https://www.youtube.com/watch?v=kJPQc0QqVMg&pp=ygUMbWF0cml4ZG90b3Jn

**Comment by heroinedor** [comment]
Decentralized identity issue on Matrix : https://github.com/matrix-org/matrix-spec/issues/203
Decentralized user account on Matrix : https://github.com/matrix-org/matrix-spec/issues/246
Portable identities issue on Matrix : https://github.com/matrix-org/matrix-spec-proposals/pull/2787

**Comment by heroinedor** [comment]
Suggestion : explain with details the pros and cons of 2 scenario : centralized matrix network with unique MXID vs federated network with multiple MXID per healthcar professional.
@heroinedor  => work on centralized scenario
@ad2ien => work on federated scenario
