### ISSUE TITLE
Experimentation double bridge IRC - Mattermost

### ISSUE THREAD

**Issue by heroinedor** [eimis-ans/eimis-synapse#118]
Question : Is it possible to to chat between 2 MI  passing through 2 bridges ?

Hypothesis : 
- installation of the 2 most advanced bridges (IRC and Mattermost ? tbc)
- intent to chat between IRC and Mattermost

Tasklist : 
- [ ] search for the most evolved bridge after IRC
- [ ] shadow user / puppet managed by IRC / Mattermost ?
- [ ] IRC installation on Kubernetes cluster (?) or use an existing server ?
- [ ] IRC bridge installation
- [ ] Mattermost installation Kubernetes cluster (if not possible to join to beta.gouv)
- [ ] Mattemost bridge installation
- [ ] Analyse in case of impossibility
- [ ] Description of configuration to be set in case of discussion

Definition of Done : 
- Discussion available => double  bridge works
- Discussion not available => analyse of the causes

**Comment by ad2ien** [comment]
Here's a docker-compose version with discord and slack : https://github.com/ad2ien/matrix-double-bridge

**Comment by ad2ien** [comment]
From what I can see, it should be possible to achieve something that would cover our needs :
- it's possible for the bridge to listen to specific events, create MX ghost users and send messages on their behalf

## Challenges:
- the puppeting, however, highly depends on the 3rd party application and can be tricky if the bridge can't create puppets on demand
- the bridged end-to-end encryption is an other challenge
