### ISSUE TITLE
Technical updates

### ISSUE THREAD

**Issue by heroinedor** [eimis-ans/eimis-synapse#121]
Tools/libraries to update : 
- [x] kubernetes : 1.25 -> 1.26
- [x] terraform provider : 0.26.0 -> 0.31.0
- [x] operator lifecycle manager : v0.23.1 ->  0.25.0
- [x] keycloak kubernetes operator : 21.0.1 -> 21.1.1
- [x] external_dns: v0.13.5 -> v0.13.6
- [ ] terraform: 1.6.0 and freeze version in workflow

**Comment by heroinedor** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/EIMIS-6419ddbd85693a00127de149/issues/eimis-ans/eimis-synapse/121?planning-poker) with Zenhub @ad2ien @JDixmier

**Comment by ad2ien** [comment]
## k8s

- last version of k8s is 1.27
- only increment minor version update is allowed so 1.25 -> 1.26 -> 1.27
- there's a couple of minutes of down time for each update
- it won't be an issue for prod env. Github env variable is already updated

**Comment by ad2ien** [comment]
external_dns update without complaining

**Comment by ad2ien** [comment]
merged
