### ISSUE TITLE
Keycloak cleanup

### ISSUE THREAD

**Issue by ad2ien** [eimis-ans/eimis-synapse#129]
Remove keycloak as a way to logging to synapse

Remove
- operator
- every keycloak related volume
- synapse extra config and configmap
- keycloak related env variable (template file and github env)

**Comment by heroinedor** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/EIMIS-6419ddbd85693a00127de149/issues/eimis-ans/eimis-synapse/129?planning-poker) with Zenhub @ad2ien
