### ISSUE TITLE
Draft a notion page based on the OKR framework  to clarify our purpose

### ISSUE THREAD

**Issue by JDixmier** [eimis-ans/eimis-synapse#134]

**Comment by JDixmier** [comment]
https://www.welcometothejungle.com/fr/articles/methode-okr-objectives-results

**Comment by heroinedor** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/EIMIS-6419ddbd85693a00127de149/issues/eimis-ans/eimis-synapse/134?planning-poker) with Zenhub @JDixmier @ad2ien
