### ISSUE TITLE
Eimis bridge User stories

### ISSUE THREAD

**Issue by heroinedor** [eimis-ans/eimis-synapse#139]
Alongside the template we could provide the user stories to complete to comply with the federation.

List US and prios for bridge development on Notion Bridges / User Stories

- [x] formulate User Stories in the notion document
- [x] add the features described on each bridge page on matrix site  Ex: https://matrix.org/ecosystem/bridges/slack/
- [ ] prioritization

the following points there #177 
- publish a public wiki page, notion page, whatever page to display the result to editor
- find a way to display the advancement of each editor's bridge

**Comment by heroinedor** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/EIMIS-6419ddbd85693a00127de149/issues/eimis-ans/eimis-synapse/139?planning-poker) with Zenhub @JDixmier

**Comment by ad2ien** [comment]
Review done by @heroinedor -> close
