### ISSUE TITLE
Secure and backup media repository

### ISSUE THREAD

**Issue by heroinedor** [eimis-ans/eimis-synapse#142]
During the migration of data from statefulset to database (see #39 ), the media repository was forgotten.
It stores the images and attachment and is currently just a pvc in kubernetes.
It should probably be mounted as an external S3 repository (to be confirmed) ?

**Comment by ad2ien** [comment]
There's a module to add to synapse to use s3 bucket for media repository : https://github.com/matrix-org/synapse-s3-storage-provider

**Comment by heroinedor** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/EIMIS-6419ddbd85693a00127de149/issues/eimis-ans/eimis-synapse/142?planning-poker) with Zenhub @ad2ien @JDixmier

**Comment by heroinedor** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/EIMIS-6419ddbd85693a00127de149/issues/eimis-ans/eimis-synapse/142?planning-poker) with Zenhub @AudeNLowpital

**Comment by ad2ien** [comment]
- [ ] create a s3 with terraform on the private network
- [ ] install the module specified above
- [ ] configuration and tests

**Comment by heroinedor** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/EIMIS-6419ddbd85693a00127de149/issues/eimis-ans/eimis-synapse/142?planning-poker) with Zenhub @AudeNLowpital

**Comment by ad2ien** [comment]
@heroinedor, I think there's no need to migrate existing files, do you agree?
