### ISSUE TITLE
Teams bridge analyze : find open source alternative

### ISSUE THREAD

**Issue by heroinedor** [eimis-ans/eimis-synapse#15]
As an eimis user,
I want to be able to chat with a health professional that as an account on teams.
In order to begin a chat with him

This implies to study the Teams bridges :  
- SaaS closed version : https://element.io/blog/ems-launches-bridging-for-microsoft-teams/ implies to get in touch with Element.
- Open source versions : 
  - old abandoned version : https://github.com/neilsb/mx-puppet-teams
  - other options : https://github.com/turt2live/matrix-wishlist/issues/16 ?
 
Tasks : 
- [x] investigate to find all open-source possibilities
- [x] analyse each possibility
- [x] write synthesis 

Definition of done : 
Synthesis of investigation.

**Comment by ch3ck** [comment]
@heroinedor what solution did you find for this?

**Comment by ad2ien** [comment]
Hi @ch3ck we tested this : https://github.com/neilsb/mx-puppet-teams not in production though

**Comment by cfoellmann** [comment]
> Hi @ch3ck we tested this : https://github.com/neilsb/mx-puppet-teams not in production though

You tested this in non-production.
What were the results?

**Comment by heroinedor** [comment]
This bridge is not production ready from our point of view, it's more like a workaround since:
- there is a kind of configuration needed by the user (it does not work out of the shell)
- it works only for the user connected, not for the entire organisation

So we decided not to use it.
