### ISSUE TITLE
Give a try to Fluffy Chat

### ISSUE THREAD

**Issue by heroinedor** [eimis-ans/eimis-synapse#68]
https://matrix.org/ecosystem/clients/
To test : Fluffy Chat.

Task list:  
- [x] list differences 
- [x] test web and android and apple
- [x] does it make sense to test this differences on end users

Definition of done:

Produce a small report compiling these results

**Comment by heroinedor** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/EIMIS-6419ddbd85693a00127de149/issues/eimis-ans/eimis-synapse/68?planning-poker) with Zenhub @ad2ien @JDixmier

**Comment by JDixmier** [comment]
Criterias : 

- [ ] Is it posible to set up a monitoring ? 
- [ ] Which client is the fastest to implement for the experimentation ?

**Comment by heroinedor** [comment]
"La question, elle est vite répondue"
Fluffy Chat android not available in France.
Fluffy Chat iOs not available at all.
=> Fluffy Chat disqualified.
