### ISSUE TITLE
Quick and dirty: Explore discovery room solution for user directory aggregation - federation with Pandalab

### ISSUE THREAD

**Issue by heroinedor** [eimis-ans/eimis-synapse#86]
As a user from eimis preprod,
I want to find another user from Pandalab with whom I have never discussed before,
In order to start a conversation with him.

Tasklist :
- [ ] federation between eimis preprod and pandalab synapse
- [ ] A hidden discovery room on every homeserver
- [ ] A dummy user per homeserver
- [ ] Join all users to their respective homeservers
- [ ] provide scripts to Pandalab to add eimis dummy users to the pandalab's discovery-room

Definition of done : 
A user from Pandalab IM instance can be found from eimis preprod instance and inversely.

**Comment by ad2ien** [comment]
On it @heroinedor, I just need the rights to push on the repo please

**Comment by ad2ien** [comment]
One last PR to merge : https://github.com/eimis-ans/discovery-rooms/pull/2

**Comment by ad2ien** [comment]
merged!
